version: '3.9'

services:
  postgres:
    image: postgres
    container_name: DB
    environment:
      POSTGRES_DB: atena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
